workspace(name = "test")

local_repository(name = "com_github_nelhage_bazel_git_repositories",
                 path = "../")

load(
    "@com_github_nelhage_bazel_git_repositories//:repositories.bzl",
    "new_native_git_repository",
    "native_git_repository",
)

new_native_git_repository(
    name = "io_bazel_rules_scala",
    remote = "https://github.com/bazelbuild/rules_scala.git",
    commit = "7b891adb975b4e3e6569b763d39ab6e9234196c9",
    build_file_contents = """
filegroup(
  name="readme",
  srcs=["README.md"],
  visibility=["//visibility:public"],
  )
"""
)


