workspace(name = "test")

load("@bazel_tools//tools/build_defs/repo:git_repositories.bzl",
     "new_git_repository",
     "git_repository")

new_git_repository(
    name = "io_bazel_rules_scala",
    remote = "https://github.com/bazelbuild/rules_scala.git",
    commit = "7b891adb975b4e3e6569b763d39ab6e9234196c9",
    build_file_content = """
filegroup(
  name="readme",
  srcs=["README.md"],
  visibility=["//visibility:public"],
  )
"""
)
